### ISSUE TITLE
Unhandled exception occured when running 0.2.0

### ISSUE THREAD

**Issue by DexLuther** [johnkiddjr/PlexMatch-File-Generator#11]
I gave 0.2.0 a whirl
I tried with this: `"F:\Plex Content\PlexMatchGenerator-Windows-x86.exe" --url http://10.0.0.154:32400 --token [TOKEN REMOVED]`
And get this:
```
[02:08:01 INF] Logger attached. Startup complete. Running file generator...
[02:08:02 ERR] An unhandeled exception occurred details below:
[02:08:02 ERR] Exception Type: System.ArgumentOutOfRangeException
[02:08:02 ERR] Exception Message: Length cannot be less than zero. (Parameter 'length')
[02:08:02 ERR] Exception Source: System.Private.CoreLib
[02:08:02 ERR] Exception Stack Trace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at PlexMatchGenerator.Services.GeneratorService.<>c.<Run>b__2_2(IMediaPath pml)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PlexMatchGenerator.Services.GeneratorService.Run(GeneratorOptions options)
```
I downloaded v0.1.4-alpha again and ran the the command line posted above and everything worked fine except that it didn't catch the movies in my library.

**Comment by johnkiddjr** [comment]
This looks like a case of the good 'ole I forgot to reverse the slashes for Windows in the code. Should have a bugfix for this later this afternoon
