### ISSUE TITLE
System NullReferenceException

### ISSUE THREAD

**Issue by Findarato** [johnkiddjr/PlexMatch-File-Generator#27]
I have a new Null Reference Exception,  Running the newest verion

```bash
joe@v-plex:~$ ./PlexMatchGenerator-Linux-x64 -u http://v-plex.telaranrhiod.space:32400 -t <MY CODE>
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexMatchGenerator.Helpers.ArgumentHelper.ProcessCommandLineResults(String plexToken, String plexUrl, List`1 rootPaths, String logPath)
   at PlexMatchGenerator.Helpers.CommandHelper.<>c__DisplayClass0_0.<<GenerateRootCommandAndExecuteHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I am once again running this from the plex host. Which is fully updated.

```Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-109-generic x86_64)```

**Comment by johnkiddjr** [comment]
@Findarato This issue should be fixed in v0.4.4-beta
